server:
  port: 6100

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

dubbo:
  application:
    name: spring-boot-demo-dubbo-consumer
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
