server:
  port: 6100

debug: true

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

dubbo:
  application:
    name: spring-boot-demo-dubbo-consumer
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.xd.springbootdemo.domain
  configuration:
    #如果数据库中的命名是xx_xx ，pojo中的对象是xxXx，此时注解的方式就是映射不上，解决如下
    map-underscore-to-camel-case: true
