server:
  port: 6100

debug: true

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 87654321
    driver-class-name: com.mysql.cj.jdbc.Driver

dubbo:
  application:
    name: spring-boot-demo-dubbo-consumer
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
