spring:
  redis:
    #redis的模式，1：单机，2：sentinel，3：cluster
    model: 3
    #    database:
    #    host:
    #    port:
    password: 123456
    ssl: false
    timeout: 60000
    cluster:
      nodes: 10.211.55.5:6379