server:
  port: 8001
  servlet:
    # 应用访问路径
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 800
      min-spare: 10

# 日志配置
logging:
  level:
    com.xd.springboot: debug
    org.springframework: warn

debug: true

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active:
  redis:
    redisson:
      config:
        file: classpath:redisson.yml

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.xd.springbootdemo.domain
  configuration:
    #如果数据库中的命名是xx_xx ，pojo中的对象是xxXx，此时注解的方式就是映射不上，解决如下
    map-underscore-to-camel-case: true
